### ISSUE TITLE
Not enough tasks

### ISSUE THREAD

**Issue by KonPap18** [dmst-sweng/git-intro#3]
I noticed that all of the contributors who have already select tasks, put their name asside the main task, instead of a subtask. The tasks were already short for the number of the contributors so it would be nice if every one chose one sub-task and not the whole task.I am interested for the example for the "Class names should follow unanimous style (e.g. AdventureStory, ScaryStory)" task.Is it ok @mfragkoulis , or we should come up with new tasks?

**Comment by ppeponis** [comment]
yes i noticed that too. i am interested in task: "Option -z does not work properly"

**Comment by mfragkoulis** [comment]
Hi @KonPap18 and @ppeponis,
I'm on it.
I am informing the committers to select subtasks instead.
Stay tuned to select to-be-available subtasks shortly.
Or you can go ahead and create new (sub)tasks.
