### ISSUE TITLE
Conflict in merging master with add-substory branch.

### ISSUE THREAD

**Issue by Melmel** [dmst-sweng/git-intro#5]
Hello! I have been having this issue a few hours now, and since I was not able to resolve the conflicts alone I would please need some help with this.

I have my branch updated with all the changes I want to make to ExcitingStory.java, but when I try to merge locally master and branch it says there are conflicts and won't let me merge the master and branch java files!

Some variables were using the same values, I corrected that, but aside from that I cannot comprehend what might be wrong!! Any help would be very welcomed!

**Comment by mfragkoulis** [comment]
I am not sure what type of conflict you have, but the following tackles the most probable cause:

https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

If you continue to have trouble, continue commenting on this issue :-)

**Comment by Melmel** [comment]
Actually after downloading and installing meld (with Python and PyGTK), and had managed to resolve the conflicts in the .java file caused by the commit of k-karakatsanis , theosotr committed his changes, regarding the code alignment and made everything even more difficult to manage.

Meld showcased so many conflicts that made the modification of the final file really difficult.

What I did, was to actually download the .java file with all the commits from k-karakatsanis  and theosotr, and pasted in there my code. Then, I updated my master from the original, and rebased my branch with master. Then I added the .java file with my commits to my branch, and merged master with branch. The merge was automated and did not even need a mergedtool!!! So I pushed my commit.

**Comment by Melmel** [comment]
I will also add tomorrow these steps I took, to my Changelog file. 
However, should maybe theosotr align the code once again now that I have also committed my part?

**Comment by mfragkoulis** [comment]
It's OK, you can leave it at that, but please note the following.
I haven't used Meld but by downloading files and copying/pasting code
we circumvent Git and, thus, distract project history, make it hard to identify
commit changes, and hamper collaboration.
You can take a look at the commit history where you have removed and re-introduced the
source file to see what I mean.
Also, you had to reapply commits (I see "once again" in some commit messages).
Does @theosotr have to re-apply changes he made?

**Comment by Melmel** [comment]
No in that case do not worry because in the end I did not use Meld in merging, it was much easier without it and the commit to origin master was done based only on git bash commands. Moreover what I meant by copy pasting was that in the end I I was very confused about the changes I had locally, that I decided to git pull for my master branch, git pull for my add-substory branch, git rebase master for my add-substory branch and then applied my changes on the  .java file. Then I typed git add and git commit for my modified file in add-substory branch, then merged master with branch ()

**Comment by Melmel** [comment]
The merge was done automatically without meld and then I pushed my final commit to origin master. That way all the intermediate commits from other users were kept and my final commit was just the code I added and the Changelog. No need for anyone to reapply their commits.

**Comment by Melmel** [comment]
Hello Mr. @mfragkoulis should I close this issue? I would also like to inform you that I have updated my Changelog file with the steps I took in order to push my final commit.

**Comment by mfragkoulis** [comment]
Thank you for this notification @Melmel.
Yes please close the issue.

**Comment by Melmel** [comment]
Ok!
